-- COMANDOS PARA CRIAR E APAGAR DATABASE

CREATE DATABASE EXEMPO1;
DROP DATABASE EXEMPO1

-- COMANDOS PARA CRIAR TABELAS

CREATE TABLE FUNCIONARIOS (
id_funcionarios SERIAL NOT NULL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	status INT NOT NULL,
	cidade VARCHAR(50)
)

CREATE TABLE PRODUTOS(
id_produtos INT NOT NULL PRIMARY KEY,
nome_produtos VARCHAR(255) NOT NULL,
quantidade_produtos INT NOT NULL,
valor_produtos DECIMAL (7,2) NOT NULL,
validade_produtos DATE NOT NULL,
	FOREIGN KEY id_fucionarios REFERENCES FUNCIONAIOS --CHAVE ESTRANGEIRA 
	
)

CREATE TABLE MODELO (
id_modelo INT NOT NULL PRIMARY KEY
)

-- comando para apagar tabelas

DROP TABLE MODELO


-- COMANDO PARA VISUALIZAR RESULTADOS

SELECT * FROM FUNCIONARIOS, PRODUTOS

-- COMANDOS PARA ALTERAR CAMPOS DE TABELA
ALTER TABLE funcionarios ABORT
ADD sexo CHAR(1)
ALTER TABLE funcionarios ABORT
DROP COLUMN sexo

ALTER TABLE  funcionarios
RENAME Cidade TO City

ALTER TABLE funcionarios 
RENAME COLUMN nome VARCHAR (30); 