CREATE TABLE fORNECEDOR
(
	fcodigo SERIAL PRIMARY KEY,
	fnome VARCHAR (100),
	status VARCHAR (30) DEFAULT 'ATIVO',
	cidade VARCHAR (100)

);

CREATE TABLE PECA
(
	pcodigo SERIAL PRIMARY KEY NOT NULL,
	pnome VARCHAR (100) NOT NULL,
	cor VARCHAR (50) NOT NULL,
	cidade VARCHAR (100) NOT NULL,
	peso INT
);

CREATE TABLE INSTITUICAO
(
	icodigo SERIAL PRIMARY KEY,
	nome VARCHAR (100)
	
);

CREATE TABLE PROJETO
(
	prcodigo SERIAL PRIMARY KEY,
	prnome VARCHAR (100),
	cidade VARCHAR (100),
	icodigo INT REFERENCES INSTITUICAO(icodigo)
);

CREATE TABLE FORNECIMENTO
(
	fcodigo INT REFERENCES FORNECEDOR (fcodigo),
	pcodigo INT REFERENCES PECA (pcodigo),
	prcodigo INT REFERENCES PROJETO (prcodigo),
	quantidade INT
);

SELECT * FROM FORNECEDOR, PECA, INSTITUICAO, PROJETO, FORNECIMENTO

-- criando index para facilitar pessquisa em caso de ter muitos dados
CREATE INDEX IDX_FORNECEDOR_fNOME ON FORNECEDOR (fnome);
CREATE INDEX IDX_PECA_CIDADE ON PECA (cidade);
CREATE INDEX IDX_INSTITUICAO_NOME ON INSTITUICAO (nome);
CREATE INDEX IDX_PROJETO_PRCODIGO ON PROJETO (prcodigo);
CREATE INDEX IDX_FORNECIMENTO_QUANTIDADE ON FORNECIMENTO (quantidade);


