-- EXCLUINDO O INSTITUICAO
DROP TABLE instituicao;

-- CRIANDO UMA NOVA TABELA
CREATE TABLE CIDADE(
	CCODIGO SERIAL PRIMARY KEY,
	cnome VARCHAR (100),
	UF VARCHAR (2)
	
)
-- ADICIONANDO AS NOVAS COLUNAS E REMOVENDO AS ANTIGAS
ALTER TABLE FORNECEDOR(
	DROP COLUMN CIDADE,
	ADD COLUMN CCODIGO REFERENCES CIDADE(CCODIGO)
	
)
ALTER TABLE PECA(
	DROP COLUMN CIDADE,
	ADD COLUMN CCODIGO REFERENCES CIDADE(CCODIGO)
	
)
ALTER TABLE projeto(
	DROP COLUMN CIDADE,
	DROP COLUMN ICODIGO,
	ADD COLUMN CCODIGO REFERENCES CIDADE(CCODIGO)
	
)